cpu_core/mem.v
cpu_core/LLbit_reg.v
cpu_core/if_id.v
cpu_core/hilo_reg.v
cpu_core/div.v
cpu_core/ex_mem.v
cpu_core/pc_reg.v
cpu_core/ctrl.v
cpu_core/id_ex.v
cpu_core/ex.v
cpu_core/openmips.v
cpu_core/defines.v
cpu_core/regfile.v
cpu_core/id.v
cpu_core/cp0_reg.v
cpu_core/mem_wb.v
axi_lite_bus/axi_interconnect.v
axi_lite_bus/axi_bus_if.v
soc_top/mysoc.v
soc_top/mydefines.v
soc_top/myinst_rom.v
soc_top/mydata_ram.v
soc_top/ipguan/confreg/confreg.v
soc_top/ipguan/pwm/pwm.v
soc_top/ipguan/gpio/gpio.v
soc_top/ipguan/spi/spi_fifo4.v
soc_top/ipguan/spi/spi_top.v
soc_top/ipguan/spi/simple_spi_top.v
soc_top/ipguan/uart/uart_rfifo.v
soc_top/ipguan/uart/fifo_uart/fifo_uart.v
soc_top/ipguan/uart/fifo_uart/temp/FIFO/fifo_define.v
soc_top/ipguan/uart/fifo_uart/temp/FIFO/fifo_uart_tmp.v
soc_top/ipguan/uart/fifo_uart/temp/FIFO/fifo_parameter.v
soc_top/ipguan/uart/fifo_uart/fifo_uart_tmp.v
soc_top/ipguan/uart/uart_tx.v
soc_top/ipguan/uart/uart_rx.v
soc_top/ipguan/uart/uart_top.v
soc_top/ipguan/uart/uart_tfifo.v
soc_top/ipguan/uart/baudgen.v
soc_top/ipguan/hpet/hpet.v
soc_top/ipguan/i2c/i2c_top.v
soc_top/ipguan/i2c/i2c_master_bit_ctrl.v
soc_top/ipguan/i2c/i2c_slave_bit_ctrl.v
soc_top/ipguan/i2c/i2c_slave_byte_ctrl.v
soc_top/ipguan/i2c/i2c_master_byte_ctrl.v
test_bench/myopenmips_min_sopc_tb.v
